_tradenet/Overview/annexes-and-appendices.md
_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Deleted Annex E at https://www.customs.gov.sg/businesses/national-single-window/overview/annexes-and-appendices
Amended Step 1 at https://www.customs.gov.sg/businesses/national-single-window/overview/competent-authorities-requirements

Amend to CA contact list

---

_strategic-goods-control/Overview/scope-of-control.md

Inserted a closed bracket to the paragraph under the controlled items as there is no closed bracket and the code for target blank is displayed.

Update file: scope-of-control.md

---

_establishing-customs-value-for-imports/Establishing Customs Value for Imports/transfer-pricing-adjustments-on-imports.md

Update file: transfer-pricing-adjustments-on-imports.md

---

_certificates-of-origin/Certificates of Origin/asean-wide-self-certification-scheme.md
_certificates-of-origin/Certificates of Origin/electronic-origin-data-exchange-system-eodes-with-china.md
_temporary-import-scheme/For more information/approved-wine-event.md

Update file: electronic-origin-data-exchange-system-eodes-with-china.md

---

_CWC-licensing-requirements/Licensing Requirements/application-for-licence.md

Removal of unit’s 10-day service standard on our corporate website for CWC licence applications.

Update file: application-for-licence.md

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md
_transhipment-procedures/Transhipment Procedures/permit-amendments-and-cancellation.md

Announcement is to update licensees regarding the Annual Declaration of Past Activities (ADPA) Exercise for Year 2021.

Addition of new announcement on Announcement subpage

---

news-and-media/circulars/_posts/2021-12-23-file-Claiming Of Preferential Tariff Benefits For Goods Imported From Parties To Singapore Under The RCEP.md
news-and-media/circulars/_posts/2021-12-23-file-Claiming Preferential Tariff Benefits For Goods Exported From Singapore To Parties Under The RCEP.md

Circular updates

---

_about-us/customs-advisory-council.md
_businesses/Importing Goods/import-procedures.md

Changes to CAC members, Hd P&R approval sought.

CAC page updates

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of existing announcement in ‘Announcement’ page due to end of exercise.

Removal of existing CWC Licence Renewal Exercise for Year 2021 announcement in ‘Announcement’ page.

---

_businesses/Customs' Schemes, Licences & Framework/air-store-bond-scheme.md
_businesses/Customs' Schemes, Licences & Framework/bonded-truck-scheme.md
_businesses/Customs' Schemes, Licences & Framework/company-declaration-scheme.md
_businesses/Customs' Schemes, Licences & Framework/container-freight-warehouse-licence.md
_businesses/Customs' Schemes, Licences & Framework/duty-free-shop-scheme.md
_businesses/Customs' Schemes, Licences & Framework/excise-factory-scheme.md
_businesses/Customs' Schemes, Licences & Framework/export-transhipment-and-transit.md
_businesses/Customs' Schemes, Licences & Framework/licensed-warehouse-scheme.md
_businesses/Customs' Schemes, Licences & Framework/petroleum-and-biodiesel-blends-licences.md
_businesses/Customs' Schemes, Licences & Framework/secure-trade-partnership-stp-stp-plus.md
_businesses/Customs' Schemes, Licences & Framework/trade-first.md
_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md
news-and-media/notices/_posts/2021-12-31-file-182021 TradeNet Extended Downtime.md

insertion of latest tradefirst self assessment checklist (8 Nov version) into Customs schemes administered by SEB

Insertion of latest tradefirst self assessment checklist

---

_businesses/Valuation, Duties, Taxes & Fees/refund-of-duties-gst.md
_individuals-going-through-customs/Arrivals/declaration-and-payment-of-taxes.md

Editiorial amendment to How to Apply for Refund.

Update file: refund-of-duties-gst.md

---

_businesses/Exporting Goods/controlled-and-prohibited-goods-for-export.md
_businesses/Importing Goods/controlled-prohibited-goods-for-import.md
_businesses/Transhipping Goods/controlled-and-prohibited-goods-for-transhipment.md
_competent-authorities-requirements/Competent Authorities Requirements/singapore-police-force-arms-and-explosives-a-e-police-licensing-regulatory-department-plrd.md

Amended import, export and transhipment procedures. As well as SPF's Acts.

Amendments of Content

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of ADPA2021 announcement from the corporate website due to end of exercise.

Update file: announcement.md

---

_businesses/Customs' Schemes, Licences & Framework/excise-factory-scheme.md
_businesses/Customs' Schemes, Licences & Framework/trade-first.md
_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md

Amendments made to EFS, ZGS & TF webpage

SEB website amendments

---

_businesses/Exporting Goods/overview.md
_businesses/Importing Goods/overview.md
_businesses/Transhipping Goods/overview.md
_certificates-of-origin/Certificates of Origin/How to apply for Ordinary Certificate of origin (OCO) or Preferential Certificate of Origin (PCO).md
_export-procedures-requirements/Exporting Requirements/documentation-for-clearance-of-goods.md
_import-procedures-req/Importing Requirements/documents-for-clearance-of-goods.md
_transhipment-procedures-requirements/Transhipment Requirements/documentation-for-clearance-of-goods.md

Amended H1 permit condition in the web by removing references made to "endorsement" due to ICA's paperless clearance initiative.

Amended permit condition

---

_businesses/Customs' Schemes, Licences & Framework/apex-licence.md
_businesses/Customs' Schemes, Licences & Framework/company-declaration-scheme.md
_businesses/Customs' Schemes, Licences & Framework/consolidated-declaration.md
_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md

Removal of Hotline phone numbers from the SEB schemes webpages and inclusion of mandatory critiera for TradeFIRST

SEB amendments to the various schemes

---

_registration-services/Registration Services/authorise-a-declaring-agent.md

Amendment to the "Authorise a Declaring Agent" webpage

Website amendments (SEB)

---

_businesses/Customs' Schemes, Licences & Framework/trade-first.md

i.	Make clear that the 3 to 4 months processing timeline, upon complete submission of relevant documents, would apply to all new, renewal and supplementary applications; 
ii.	Remove the term “conditional approval” as such term is no longer valid; 
iii.	Amend the FAQs for specific business operations (e.g. multiple sites/schemes) for better clarity; and 
iv.	Editorial amendments and removal of obsolete information.

Amendments to the Customs Webpage (TradeFIRST Page)

---

_businesses/International Data Exchange/asean-customs-declaration-document-acdd.md

Update file: asean-customs-declaration-document-acdd.md

---

_businesses/Chemical Weapons Convention (CWC)/controlled-chemicals.md

Fixed broken link under "Determining if your product is controlled" > the link for "list of scheduled chemicals".

Update file: controlled-chemicals.md

---

_tradenet/Overview/tradenet-front-end-solution-providers.md

Updated TradeNet Frontend Vendor's name and email address.

Update file: tradenet-front-end-solution-providers.md

---

_eservices/customs-forms-service-links.md

amending broken link as reported by traders

Update file: customs-forms-service-links.md

---

_eservices/customs-forms-service-links.md

update the broken link in eServices / Customs forms & service links > Customs Schemes, Permit & licence > 
3. Application for Duty Exemption of Dutiable Goods by Industrial Users
9. Application for Licensed Premises.

amend broken link

---

_eservices/customs-forms-service-links.md

ASEAN Customs Transit System/Declaration Document
Point 3 & 5 
Customs’ Schemes, Permit & Licences
Point 7, 8 & 16

Amended broken links and spelling errors located at Customs Forms & Service Links webpage.

---

_business-resources/Courses and Events/events-for-traders.md
_business-resources/collection.yml
_businesses/Strategic Goods Control/import-certificate-and-delivery-verification.md
_import-certificate-and-delivery-verification/Import Certificate and Delivery Verification/delivery-verification.md
_import-certificate-and-delivery-verification/Import Certificate and Delivery Verification/import-certificate.md

Import Certificate: Amend 'A maximum of 20' to 10; '(for example, 12 tonnes, 5 pieces)' to 12 TNE, 5 NMB under subheader "Completing an IC Application"  
Delivery Verification: Remove 'your ICDV via NTP' from subheader "Applying for Delivery Verification".
Import Certificate and Delivery Verification: Amend 'The goods imported into Singapore are controlled by the exporting country, or' to and under subheader "Import Certificate and Delivery Verification"

Text amendments for subpages under Import Certificate and Delivery Verification

---

_businesses/International Data Exchange/asean-customs-declaration-document-acdd.md

Added Brunei to ACDD Exchange Ready AMS.

Added Brunei to ACDD Exchange Ready AMS

---

_eservices/customs-forms-service-links.md
_export-procedures-more/Export Procedures/exporting-hand-carried-commercial-goods.md

To include link to form which allow businesses to query the clearance status of HCES permits

Update file: exporting-hand-carried-commercial-goods.md

---

_about-us/customs-advisory-council.md

Updated Mr Tan Yock Juee membership in CAC page.
Hd P&R approval sought, CComs concurrence sought.

Update file: customs-advisory-council.md

---

_businesses/Strategic Goods Control/strategic-goods-control-list.md
_strategic-goods-control/Overview/legislation.md

Dear Isabel,
For your approval please. Thank you.

Update of hyperlink for Strategic Goods Control Order 2021

---

_CWC-licensing-requirements/Licensing Requirements/application-for-licence.md
_businesses/Chemical Weapons Convention (CWC)/announcement.md

-	Removal of existing ADAA 2023 announcement in ‘Announcement’ page 
-	Revision of the subheader to align with ISO SOP CUS-TD-006

Removal of ADAA2023 announcement and revision of subheader

---

_competent-authorities-requirements/Competent Authorities Requirements/national-parks-board-cites.md

Updated NParks - CITES webpage.

Update file: national-parks-board-cites.md

---

_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

BSB broken link

---

_businesses/Valuation, Duties, Taxes & Fees/permits-documentation-and-other-fees.md

Update file: permits-documentation-and-other-fees.md

---

_competent-authorities-requirements/Competent Authorities Requirements/ministry-of-health-biosafety-branch.md
_competent-authorities-requirements/Competent Authorities Requirements/singapore-police-force-public-entertainment-liquor-licensing-division-pelu-police-licensing-regulatory-department-plrd.md

additional amendment to BSB CA

additional amendment to BSB CA

---

_competent-authorities-requirements/Competent Authorities Requirements/import-and-export-of-goods-covered-under-import-certificate-and-delivery-verification-icdv.md
_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-basel-convention.md
_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Updated CAs' webpage

---

_businesses/border-enforcement-of-intellectual-property-rights.md
_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-hazardous-substances.md
_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-ozone-depleting-substances.md
_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-rotterdam-convention-pic-procedure.md
_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Updated NEA webpages

---

_registration-security-lodgement/Security Lodgement/how-to-lodge-security.md

Hi Isabel,
Amended a weblink at the security lodge page.

Update file: how-to-lodge-security.md

---

_businesses/International Connectivity/Container Track and Trace.md

Removing a liner on the availability of the service

Update file: Container Track and Trace.md

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Addition of new announcement to update licensees regarding the Annual Declaration of Past Activities (ADPA) Exercise for Year 2022.

New announcement

---

_businesses/Exporting Goods/overview.md
_businesses/Importing Goods/overview.md
_businesses/Transhipping Goods/overview.md
_export-procedures-more/Export Procedures/types-of-export-permits.md
_export-procedures-requirements/Exporting Requirements/apply-for-customs-export-permit.md

Hi Isabel,
Amended serveral pages regarding permit fee. For your assistance for pull request. 
Thank you.

Update on permit fee on customs website

---

_businesses/Exporting Goods/overview.md
_businesses/Importing Goods/overview.md
_businesses/Transhipping Goods/overview.md
_export-procedures-more/Export Procedures/types-of-export-permits.md
_export-procedures-requirements/Exporting Requirements/apply-for-customs-export-permit.md

Hi,
Change from "Please click" to "Please refer to".
Thank you.

minor amendment.

---

_authorised-piers-places/Authorised Piers and Places/other-piers-and-places.md

Hi,
Have amended Other Piers and Places webpage.
Thank you.

Amended Other Piers and Places Page

---

_tradenet/Overview/tradenet-front-end-solution-providers.md

remove bluejay fax no.

---

pages/Contact Us.md

remove duplication "Send us a feedback"

Update file: Contact Us.md

---

_eservices/Manifest Reconciliation Statement (MRS) Scheme/manifest-reconciliation-statement-scheme.md

Update file: manifest-reconciliation-statement-scheme.md

---

_businesses/Customs' Schemes, Licences & Framework/export-transhipment-and-transit.md

Added a liner to the STS page to make clear the usage of the bulk permit.

Update file: export-transhipment-and-transit.md

---

_eservices/customs-sg-web-application.md

Further amended notification banner for Customs@SG notification for Budget Day

Updated Customs@SG Web Application webpage

---

_eservices/customs-sg-web-application.md

Removed maintenance notification following Budget Day announcement.

Update file: customs-sg-web-application.md

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of Annual Declaration of Past Activities (ADPA) Exercise for Year 2022 announcement as the deadline for submission is 31 Jan 2023.

Removal of Annual Declaration of Past Activities (ADPA) Exercise for Year 2022

---

_businesses/Customs' Schemes, Licences & Framework/trade-first.md

Removal of CDS scheme from the main TradeFIRST page.

Update file: trade-first.md

---

_eservices/customs-forms-service-links.md

Removal of additional '77' from Item No. 7 under Strategic Goods Control

Removal of additional '77' from Item No. 7 under Strategic Goods Control

---

_competent-authorities-requirements/Competent Authorities Requirements/Singapore Food Agency (Rice).md

Update Customs website for transition of RCU from ESG to SFA

Update Customs website for transition of RCU from ESG to SFA

---

_competent-authorities-requirements/Competent Authorities Requirements/Singapore Food Agency (Rice).md
_competent-authorities-requirements/collection.yml
_eservices/customs-forms-service-links.md

Update of RCU page

---

_businesses/Customs' Schemes, Licences & Framework/secure-trade-partnership-stp-stp-plus.md
_eservices/customs-forms-service-links.md

Replacing 2 links in Customs forms & links and the removal of Account manager in the STP webpage

SEB amendments to webpage

---

_redirects

Reverts isomerpages/singapore-customs-cms#365

Revert "Update redirect"

---

_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md
news-and-media/circulars/_posts/2023-05-12-file-082023 Changes to the Prohibition of Exports, Transhipments and Goods In Transit to Somalia.md

Dear Isabel,
I have uploaded the Circular 08/2023 Changes to the Prohibition of Exports, Transhipments and Goods In Transit to Somalia through Singapore. For your approval, please. Thank you.
Regards,
Emily

Circular 08/2023 Changes to the Prohibition of Exports, Transhipments and Goods In Transit to Somalia through Singapore

---

_businesses/ASEAN Customs Transit System (ACTS)/registration-and-acts-declaration.md

Hi Isabel,
Did editorial change. There was no change of content.
Thank you.

Editorial Changes

---

_temporary-import-scheme/Temporary Export/temporary-export-duration-and-extension.md

Hi Isabel,
Content edited. 
Thank you.

Amended Temporary Export Duration and Extension

---

_individuals-going-through-customs/Arrivals/duty-free-concession-and-gst-relief.md

changes to content on GST import relief, cleared by MOF.

changes to content on GST import relief, cleared by MOF.

---

_individuals-going-through-customs/Arrivals/duty-free-concession-and-gst-relief.md

minor edits. spacing and "up to" in table

minor edits: spacing + added words in table

---

_businesses/Strategic Goods Control/permit-and-registration-requirements.md

Amended text for greater clarity.
A strategic goods permit is required for: 
•	Any transfer (export, transhipment, transit, and/ or intangible transfer) of strategic goods and related technology listed in the Strategic Goods Control List; and
•	Any transfer (export, transhipment, transit, intangible transfer, and/ or brokering) of goods or technology, which is intended or likely to be used for or in connection with weapons of mass destruction.

Permit and Registration Requirements

---

_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md

To address a broken link in the ZGS webpage

Amendment to ZGS webpage to resolve broken link

---

_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Update broken link for RPNSD

---

_eservices/customs-forms-service-links.md

Update the docs links from PDF to Word Doc, so to allow coys to fill in the forms more conveniently.

Streamlined End-User Statement/Certificate Submission for UNSC/CWC/SGC permits 

---

news-and-media/publications/_posts/2023-07-05-post-Statistics.md

Removed Enforcement Statistics on behalf of OPDB

Removed Enforcement Statistics

---

_strategic-goods-control/Overview/enforcement.md

For Coms' approval, please. Thank you.

Removal of Strategic Goods - Enforcement Action Stats

---

_CWC-licensing-requirements/Additional Information/licence-terms-and-conditions.md

(a)	Removal of obsolete table of information involving CWC scheduled chemicals under Category 1,2 and 3
(b)	Inclusion of working hyperlinks for NEA and SCDF

Corporate Website Content Amendments for CWC Licence Terms and Conditions (Removal of obsolete table)

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

•	To remove existing announcement on Annual Declaration for Anticipated Activities (ADAA) Exercise for Year 2024 as the exercise has ended
•	To add new announcement to update the public on the commencement of Joint Regulatory Control of Scheduled CWC Chemicals by NEA, SCDF and NA(CWC)

Corporate Website Content Amendments for Joint Regulatory Control of Scheduled CWC Chemicals by NEA, SCDF and NA(CWC)

---

news-and-media/circulars/_posts/2023-10-20-file-192023 Implementation of Revised GST Rate of 9.md
news-and-media/circulars/_posts/2023-10-20-file-202023 Implementation of Revised GST Rate of 9.md

Edited the correct number but i am unable to input the special characters to reflect the following.
Circular 20/2023 Implementation of Revised GST Rate of 9%

Amended the circular number.

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

To post new announcement to inform licensees regarding the commencement of the ADPA exercise for the year 2023.

To post new announcement to inform licensees regarding the commencement of the ADPA exercise for the year 2023.

---

_businesses/Customs' Schemes, Licences & Framework/air-store-bond-scheme.md
_businesses/Customs' Schemes, Licences & Framework/apex-licence.md
_businesses/Customs' Schemes, Licences & Framework/industrial-exemption-factory-scheme.md
_businesses/Customs' Schemes, Licences & Framework/licensed-warehouse-scheme.md
_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md

Amendments to SEB Licence Fee

---

_competent-authorities-requirements/Competent Authorities Requirements/singapore-police-force-arms-and-explosives-a-e-police-licensing-regulatory-department-plrd.md

Update broken hyperlink on AED writeup

Update broken hyperlink on AED writeup

---

_competent-authorities-requirements/Competent Authorities Requirements/health-science-authority-hsa.md
_eservices/customs-sg-web-application.md

Update HPR writeup

---

_competent-authorities-requirements/Competent Authorities Requirements/Singapore Food Agency (Rice).md
_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Update CA content on website

---

_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Editorial amendment to remove {:target="_blank"})

Editorial amendment to remove {:target="_blank"})

---

_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Update broken link

---

_temporary-import-scheme/Temporary Export/permit-application-procedures.md
news-and-media/advisories/_posts/2020-08-14-advisory.md

…14-advisory.md","userId":"378"}

Fixed broken link on scam advisory page

---

_businesses/Importing Goods/controlled-prohibited-goods-for-import.md

Remove AED Prohibited Goods

---

_businesses/Acts and Subsidiary Legislation/customs-act.md

Update Invalid Link embedded in "Customs" Act page on Customs Corporate Website

Update Invalid Link embedded in "Customs" Act page on Customs Corporate Website 

---

_businesses/Customs' Schemes, Licences & Framework/container-freight-warehouse-licence.md
_businesses/Customs' Schemes, Licences & Framework/licensed-warehouse-scheme.md
_businesses/Customs' Schemes, Licences & Framework/zero-gst-warehouse-scheme.md

SEB Customs Website Amendment

---

_about-us/customs-advisory-council.md

Change in CAC members list on Customs website- removal of Mr Chris Charlton's name on website.

Change in CAC members list on Customs website 

---

_competent-authorities-requirements/Competent Authorities Requirements/info-communications-media-development-authority-imda-radiocomm-dealer-licensing.md

Update IMDA writeup on website

Update IMDA writeup on website

---

_competent-authorities-requirements/Competent Authorities Requirements/info-communications-media-development-authority-imda-radiocomm-dealer-licensing.md

To remove the {:target="_blank"} tag since it is not recognised by the new editor

To remove the {:target="_blank"} tag

---

_eservices/customs-forms-service-links.md

SEB - Customs Website Content Amendments - New FormSG Link

SEB - Customs Website Content Amendments - New FormSG Link

---

_competent-authorities-requirements/Competent Authorities Requirements/Singapore Food Agency (Rice).md
_tradenet/Overview/competent-authorities-requirements-for-controlled-items.md

Update Rice writeup on website

Update Rice writeup on website

---

_eservices/customs-sg-web-application.md

Amended the hyperlink as "Customs@SG web application" was split into two.

Issues with hyperlink

---

_businesses/Importing Goods/controlled-prohibited-goods-for-import.md
_competent-authorities-requirements/Competent Authorities Requirements/info-communications-media-development-authority-imda-radiocomm-dealer-licensing.md

Editorial amendment on IMDA and controlled goods writeup

Editorial amendment on IMDA and controlled goods writeup

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Addition of new announcement to update licensees regarding the Annual Declaration for Anticipated Activities (ADAA) Exercise for Year 2025.

Addition of new announcement to update licensees regarding the Annual Declaration for Anticipated Activities (ADAA) Exercise for Year 2025

---

_businesses/overview.md
_transhipment-procedures-requirements/Transhipment Requirements/retaining-your-trade-documents.md

amended the broken link under "Please read the [guidelines](https://www.customs.gov.sg/news-and-media/notices/46_Notice_05_2015_Ver1.pdf) for storing images of trade documents."

https://www.customs.gov.sg/businesses/transhipping-goods/transhipment-procedures/retaining-trade-documents/

---

_businesses/Customs' Schemes, Licences & Framework/excise-factory-scheme.md

Fixed Broken Link - SEB

---

_businesses/International Connectivity/Container Track and Trace.md
_businesses/National Single Window/networked-trade-platform.md
_businesses/National Single Window/overview.md
_export-procedures-more/Export Procedures/exporting-hand-carried-commercial-goods.md

- Update the retrieval of digital clearance file on NTP & update circular link
- Remove "data repository" from NTP write up
- Update NTP write up & removed links that are no longer relevant with revamp of NTP website
- Update page Track & Trace service

NTPO Amendments

---

_businesses/Customs' Schemes, Licences & Framework/TradeFIRST.md

Removal of ACDD on Website

---

_strategic-goods-permit-and-reg-req/Permit and Registration Requirements/Bulk Permit: Export, Transhipment and Transit.md

Amendment to broken link on application for individual permit

Amendment to broken link 

---

_eservices/customs-sg-web-application.md

jonlcob: new payment modes for C@SG: added unionpay, JCB, ApplePay and GooglePay. thanks!

jonlcob: new payment modes for C@SG

---

_about-us/customs-advisory-council.md
_eservices/customs-sg-web-application.md
_eservices/payment-to-customs.md

Removing para on SingPost in eservices ; payment to customs.

Removing para on SingPost in eservices ; payment to customs

---

_data/footer.yml
_data/navigation.yml
_includes/chatbot-scripts.html

Onboard to AskGov, and amend the FAQ link

Onboard to AskGov and amend FAQ

---

_individuals-going-through-customs/Arrivals/duty-free-concession-and-gst-relief.md

Updated webpage on Duty Free Concession and GST Relief

---

_about-us/careers.md

Edits to Career page

---

_businesses/Customs' Schemes, Licences & Framework/TradeFIRST.md

update go.gov link

---

_eservices/customs-sg-web-application.md
_individuals-going-through-customs/Arrivals/duty-free-concession-and-gst-relief.md

Updated classification of liquor products

---

_businesses/Strategic Goods Control/resources.md

To update broken links

---

_competent-authorities-requirements/Competent Authorities Requirements/singapore-civil-defence-force-scdf.md

Update broken link on SCDF writeup

Update broken link on SCDF writeup

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of ADAA 2025 announcement and proposed changes to the existing page is recorded in tracked changes as the exercise has ended.

Removal of ADAA 2025 announcement 

---

_businesses/Strategic Goods Control/useful-links.md

Update broken links

---

_eservices/Customs Forms & Service Links.md
_strategic-goods-control-list/Strategic Goods Control List/determination-of-strategic-goods.md
pages/Contact Us.md
pages/feedback.md

https://www.customs.gov.sg/eservices/customs-forms-and-service-links
Updated Annex A - Product Questionnaire A-1, A-2 and A-3

Uploading of reviewed forms which are effective from 01 Oct 2024

---

_strategic-goods-control/Overview/legislation.md

Updated correct document to the legis

---

_businesses/Strategic Goods Control/resources.md

Update Guidebook on the Determination of Strategic Goods

---

_importing-goods-more/Import Procedures/authorised-piers-and-places.md

…authorised-piers-and-places.md","userId":"275"}

amending for Authorised Piers and Places

---

_about-us/careers.md
pages/careers.md

Revised CUS 4 starting monthly salary to $4020 - $4830

Change to salary for Gr 4

---

_competent-authorities-requirements/Competent Authorities Requirements/national-parks-board-plant-health.md

Correct typo to Plant Health writeup

Correct typo to Plant Health writeup

---

_competent-authorities-requirements/Competent Authorities Requirements/enterprise-singapore-esg-export-of-rubber.md
_importing-dutiable-motor-vehicles-steps/Guide to Importing Dutiable Motor Vehicles/for-authorised-agents.md
_importing-dutiable-motor-vehicles-steps/Guide to Importing Dutiable Motor Vehicles/for-individuals-or-parallel-importers.md

Update link to apply for rubber export licence

Update link to apply for rubber export licence

---

pages/feedback.md

Updating of FormSG links on Customs website - Refund Feedback Form

Updating of FormSG links on Customs website - Refund Feedback Form

---

_business-resources/Courses and Events/Joint Industry Outreach on Strategic Trade Management 2024.md

…anagement 2024.md","fileName":"Joint Industry Outreach on Strategic Trade Management 2024.md","userId":"225"}

Uploaded JP slides in JIO2024

---

_businesses/Strategic Goods Control/useful-links.md
_businesses/Valuation, Duties, Taxes & Fees/permits-documentation-and-other-fees.md

Update permit and CO fee

---

pages/Contact Us.md

Hi Corp Comm Colleagues
Please assist to change the link of the appeal form on the said webpage below to this update [link](https://form.gov.sg/66ce980d21805ae7af787ff7).
Refer to [Contact Us](https://www.customs.gov.sg/contact-us/) webpage, we encountered an error “This form is not available.” when clicking on [Customs Offence Appeal Form](https://form.gov.sg/5fab8747ec6c950011f3f82d).
For your checking and update. Thank you

 Customs website - Contact Us > Customs Offence Appeal Form

---

_certificates-of-origin/Certificates of Origin/Self Certification .md

…tification .md","userId":"685"}

Update of circular on Self Certification page

---

_businesses/Strategic Goods Control/overview.md
_competent-authorities-requirements/Competent Authorities Requirements/ministry-of-health-biosafety-branch.md
_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-radiation-protection-and-nuclear-science-division-rpnsd.md

Update broken link on webpages under TNO

Update broken link on webpages under TNO

---

_about-us/careers.md
_businesses/Business Resources/eLearning.md
pages/careers.md

Changes to career pages

---

_eservices/Customs Forms & Service Links.md

Correction to 5 links

---

_eservices/Customs Forms & Service Links.md

- Remove S/N 7 under Import/Export/Transhipment

Remove HCES from Customs Forms & Service Links Page

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of existing CWC Licence Renewal Exercise for Year 2025 announcement in ‘Announcement’ page.

Removal of existing CWC Licence Renewal Exercise for Year 2025 announcement in ‘Announcement’ page.

---

_eservices/customs-sg-web-application.md

…ustoms-sg-web-application.md","userId":"920"}

Updating Customs@SG Web Application webpage

---

_businesses/Chemical Weapons Convention (CWC)/announcement.md

Removal of the announcement as the ADPA exercise for the year 2024 has ended.

Removal of the announcement as the ADPA exercise for the year 2024 has ended.

---

_businesses/International Connectivity/ASEAN Customs Declaration Document (ACDD).md

Update list of ACDD participating countries

Update list of ACDD participating countries

---

_competent-authorities-requirements/Competent Authorities Requirements/national-parks-board-plant-health.md

Update to NParks plant health page

Update to NParks plant health page

---

_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-basel-convention.md

Update NEA writeup

---

_eservices/customs-sg-web-application.md

…ustoms-sg-web-application.md","userId":"920"}

Update on Customs@SG after BD

---

news-and-media/circulars/_posts/2024-09-27-file-062024 Implementation of ASEAN AEO Mutual Recognition Arrangement.md
news-and-media/notices/_posts/2025-02-21-file-052025 Update to Customs Circular No 062024.md

Uploading of Notices and Circular

Uploading of Notices and Circular

---

_about-us/careers.md
pages/careers.md

To remove "and Personal Development Fund".

Remove outdated info

---

_about-us/careers.md
pages/careers.md

New salary ranges

---

_competent-authorities-requirements/Competent Authorities Requirements/national-parks-board-animal-veterinary-service-animal.md

National Parks Board/Animal & Veterinary Service (Animal) writeup amendment

National Parks Board/Animal & Veterinary Service (Animal)

---

_competent-authorities-requirements/Competent Authorities Requirements/national-environment-agency-chemical-control-and-management-department-hazardous-substances.md

National Environment Agency - Chemical Control and Management Department (Hazardous Substances) Update

National Environment Agency Update

---

_eservices/Customs Forms & Service Links.md
_importing-dutiable-motor-vehicles-steps/Guide to Importing Dutiable Motor Vehicles/for-authorised-agents.md
_importing-dutiable-motor-vehicles-steps/Guide to Importing Dutiable Motor Vehicles/for-individuals-or-parallel-importers.md

Add service standards. Remove No. 12 Application for Valuation of Tax-Exempted Motor Vehicles.

Include Service Standard. Remove form. 

---

pages/Contact Us.md

Update Contact Us

---

pages/Contact Us.md

Amendments to Contact Us page

---

_businesses/Customs' Schemes, Licences & Framework/secure-trade-partnership-stp-stp-plus.md
_competent-authorities-requirements/collection.yml

STP changes

---

_about-us/customs-advisory-council.md

…toms-advisory-council.md","userId":"81430"}

update CAC chairman
